/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.Carros;
import control.Consecionario;
import control.ReturnViews;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elkin
 */
public class Principal extends javax.swing.JFrame {
  Consecionario concesionario = new Consecionario();
    private DefaultTableModel modelo;
    public Principal() {
        initComponents();
        Contenedor.add(MenuInicio);
        MenuInicio.setVisible(true);
        CampoNombreConcesionario1.requestFocus();
        CampoNombreConcesionario1.selectAll();
        this.setExtendedState(MAXIMIZED_BOTH);
        listarCarros.pack();
        listarCarros.setLocationRelativeTo(null);
        AddCarros.pack();
        AddCarros.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        listarCarros = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        eliminarAutoTextField = new javax.swing.JTextField();
        eliminarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cantidadAutos = new javax.swing.JTextField();
        AddCarros = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        textColor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textModelo = new javax.swing.JTextField();
        atrasButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        comboMarca = new javax.swing.JComboBox<>();
        agregarButton = new javax.swing.JButton();
        ImagenAddcarro = new javax.swing.JLabel();
        AddCarroTitulo = new javax.swing.JLabel();
        MenuInicio = new javax.swing.JPanel();
        TituloConce = new javax.swing.JLabel();
        Rueda = new javax.swing.JLabel();
        Gerente = new javax.swing.JLabel();
        CampoNombreGerente = new javax.swing.JTextField();
        CampoNombreConcesionario1 = new javax.swing.JTextField();
        EnviarInformacion = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        TituloNombreConce = new javax.swing.JLabel();
        TituloNombreGerente = new javax.swing.JLabel();
        TablaInicio = new javax.swing.JTabbedPane();
        TablaBienvenida = new javax.swing.JTabbedPane();
        TablaInicioBienvenida = new javax.swing.JPanel();
        BienvenidaInicio = new javax.swing.JLabel();
        TituloNombreConce1 = new javax.swing.JLabel();
        Sonrisa = new javax.swing.JLabel();
        TablaCarros = new javax.swing.JTabbedPane();
        TablaCarrosMenu = new javax.swing.JPanel();
        TituloMenuCarros = new javax.swing.JLabel();
        AgregarCarro = new javax.swing.JPanel();
        TituloAgregarCarros = new javax.swing.JLabel();
        BotonAgregarCarro = new javax.swing.JButton();
        LogoCarroAgregar = new javax.swing.JLabel();
        ListarCarros = new javax.swing.JPanel();
        TituloListarCarros = new javax.swing.JLabel();
        BotonListarCarro = new javax.swing.JButton();
        CarroLista1 = new javax.swing.JLabel();
        CarroLista2 = new javax.swing.JLabel();
        EliminarCarros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonEliminarCarro = new javax.swing.JButton();
        TablaPersonalVentas = new javax.swing.JTabbedPane();
        TablaPersonalMenu = new javax.swing.JPanel();
        TituloPersonalVentas = new javax.swing.JLabel();
        AgregarPersonal = new javax.swing.JPanel();
        TituloAgregarPerso = new javax.swing.JLabel();
        BotonAgregarPersonal = new javax.swing.JButton();
        ListarPersonal = new javax.swing.JPanel();
        TituloListarPersonal = new javax.swing.JLabel();
        BotonListarPersonal = new javax.swing.JButton();
        EliminarPersonal = new javax.swing.JPanel();
        TituloEliminarPersonal = new javax.swing.JLabel();
        BotonElimianrPersonal = new javax.swing.JButton();
        TablaVentas = new javax.swing.JTabbedPane();
        TablaVentasMenu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        AgregarVenta = new javax.swing.JPanel();
        TituloAgregarVenta = new javax.swing.JLabel();
        BotonAgregarCompra = new javax.swing.JButton();
        TablaConfiguracion = new javax.swing.JTabbedPane();
        Configuracion = new javax.swing.JPanel();
        TituloConfiguracion = new javax.swing.JLabel();
        TituloCambiarConce = new javax.swing.JLabel();
        TituloCambiarGerente = new javax.swing.JLabel();
        CampoNuevoConce = new javax.swing.JTextField();
        CampoNuevoGerente = new javax.swing.JTextField();
        BotonCambiarDatos = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        Contenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCarro = new javax.swing.JMenuItem();
        jMenuPersonal = new javax.swing.JMenuItem();
        jMenuVentas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        listarCarros.setResizable(false);

        jLabel2.setText("Digite el Codigo del Auto a Eliminar:");

        eliminarButton.setText("ELIMMINAR AUTO");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Marca", "Modelo", "Color", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaDatos);

        jLabel3.setText("Cantidad de Autos:");

        javax.swing.GroupLayout listarCarrosLayout = new javax.swing.GroupLayout(listarCarros.getContentPane());
        listarCarros.getContentPane().setLayout(listarCarrosLayout);
        listarCarrosLayout.setHorizontalGroup(
            listarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarCarrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarAutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarCarrosLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(listarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listarCarrosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        listarCarrosLayout.setVerticalGroup(
            listarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarCarrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eliminarAutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(listarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Color:");

        textColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textColorActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Modelo:");

        textModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textModeloActionPerformed(evt);
            }
        });

        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/atras.png"))); // NOI18N
        atrasButton.setText("Atras");
        atrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButtonActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Código:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Marca:");

        textCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Precio:");

        textPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecioActionPerformed(evt);
            }
        });

        comboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mazda", "Chevrolet", "Camaro", "Ferrari", "Corsa", "Hyundai", " " }));
        comboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMarcaActionPerformed(evt);
            }
        });

        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mas.png"))); // NOI18N
        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        ImagenAddcarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AgregarCarro.png"))); // NOI18N

        AddCarroTitulo.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        AddCarroTitulo.setForeground(java.awt.Color.blue);
        AddCarroTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddCarroTitulo.setText("Agregar Carro");

        javax.swing.GroupLayout AddCarrosLayout = new javax.swing.GroupLayout(AddCarros.getContentPane());
        AddCarros.getContentPane().setLayout(AddCarrosLayout);
        AddCarrosLayout.setHorizontalGroup(
            AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCarrosLayout.createSequentialGroup()
                .addGroup(AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddCarrosLayout.createSequentialGroup()
                        .addComponent(agregarButton)
                        .addGap(31, 31, 31)
                        .addComponent(atrasButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textColor)
                    .addComponent(textPrecio)
                    .addComponent(textCodigo)
                    .addComponent(textModelo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCarrosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCarrosLayout.createSequentialGroup()
                        .addComponent(ImagenAddcarro)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCarrosLayout.createSequentialGroup()
                        .addComponent(AddCarroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        AddCarrosLayout.setVerticalGroup(
            AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCarrosLayout.createSequentialGroup()
                .addComponent(AddCarroTitulo)
                .addGap(26, 26, 26)
                .addComponent(ImagenAddcarro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarButton)
                    .addComponent(atrasButton))
                .addGap(27, 27, 27))
        );

        MenuInicio.setBackground(new java.awt.Color(73, 83, 113));
        MenuInicio.setLayout(new java.awt.GridBagLayout());

        TituloConce.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        TituloConce.setForeground(new java.awt.Color(255, 255, 255));
        TituloConce.setText("Ingrese el nombre del concesionario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 257, 0, 0);
        MenuInicio.add(TituloConce, gridBagConstraints);

        Rueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Rueda.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 449, 0, 0);
        MenuInicio.add(Rueda, gridBagConstraints);

        Gerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Gerente.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 487, 0, 0);
        MenuInicio.add(Gerente, gridBagConstraints);

        CampoNombreGerente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        CampoNombreGerente.setForeground(new java.awt.Color(204, 204, 204));
        CampoNombreGerente.setText("Nombre del concesionario...");
        CampoNombreGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreGerenteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 565;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 257, 0, 0);
        MenuInicio.add(CampoNombreGerente, gridBagConstraints);

        CampoNombreConcesionario1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        CampoNombreConcesionario1.setForeground(new java.awt.Color(204, 204, 204));
        CampoNombreConcesionario1.setText("Nombre del concesionario...");
        CampoNombreConcesionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreConcesionario1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 565;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 267, 0, 155);
        MenuInicio.add(CampoNombreConcesionario1, gridBagConstraints);

        EnviarInformacion.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        EnviarInformacion.setForeground(new java.awt.Color(255, 255, 255));
        EnviarInformacion.setText("OK");
        EnviarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarInformacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 508, 58, 0);
        MenuInicio.add(EnviarInformacion, gridBagConstraints);

        MenuPrincipal.setBackground(new java.awt.Color(116, 149, 154));

        Encabezado.setBackground(new java.awt.Color(73, 83, 113));

        TituloNombreConce.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        TituloNombreConce.setForeground(new java.awt.Color(255, 255, 255));
        TituloNombreConce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloNombreConce.setText("Concesionario de");

        TituloNombreGerente.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        TituloNombreGerente.setForeground(new java.awt.Color(255, 255, 255));
        TituloNombreGerente.setText("Gerente: ");
        TituloNombreGerente.setToolTipText("");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addComponent(TituloNombreGerente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TituloNombreConce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloNombreConce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(TituloNombreGerente)
                .addContainerGap())
        );

        TablaInicio.setBackground(new java.awt.Color(241, 224, 172));
        TablaInicio.setForeground(new java.awt.Color(241, 224, 172));

        TablaInicioBienvenida.setBackground(new java.awt.Color(73, 83, 113));

        BienvenidaInicio.setFont(new java.awt.Font("Bauhaus 93", 0, 70)); // NOI18N
        BienvenidaInicio.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidaInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BienvenidaInicio.setText("Bienvenido(a) al");

        TituloNombreConce1.setFont(new java.awt.Font("Bauhaus 93", 0, 70)); // NOI18N
        TituloNombreConce1.setForeground(new java.awt.Color(255, 255, 255));
        TituloNombreConce1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloNombreConce1.setText("Concesionario de");

        Sonrisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sonrisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sonrisa.png"))); // NOI18N

        javax.swing.GroupLayout TablaInicioBienvenidaLayout = new javax.swing.GroupLayout(TablaInicioBienvenida);
        TablaInicioBienvenida.setLayout(TablaInicioBienvenidaLayout);
        TablaInicioBienvenidaLayout.setHorizontalGroup(
            TablaInicioBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaInicioBienvenidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TablaInicioBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablaInicioBienvenidaLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(Sonrisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(424, 424, 424))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablaInicioBienvenidaLayout.createSequentialGroup()
                        .addGroup(TablaInicioBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BienvenidaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TituloNombreConce1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        TablaInicioBienvenidaLayout.setVerticalGroup(
            TablaInicioBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaInicioBienvenidaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(BienvenidaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sonrisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TituloNombreConce1)
                .addContainerGap(1596, Short.MAX_VALUE))
        );

        TablaBienvenida.addTab("Inicio", TablaInicioBienvenida);

        TablaInicio.addTab("Inicio", TablaBienvenida);

        TablaCarrosMenu.setBackground(new java.awt.Color(73, 83, 113));

        TituloMenuCarros.setFont(new java.awt.Font("Bauhaus 93", 0, 120)); // NOI18N
        TituloMenuCarros.setForeground(new java.awt.Color(255, 255, 255));
        TituloMenuCarros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloMenuCarros.setText("Menu Carros");

        AgregarCarro.setBackground(new java.awt.Color(204, 255, 204));

        TituloAgregarCarros.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        TituloAgregarCarros.setForeground(new java.awt.Color(102, 102, 102));
        TituloAgregarCarros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloAgregarCarros.setText("Agregar Carros");

        BotonAgregarCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mas_1.png"))); // NOI18N
        BotonAgregarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarCarroActionPerformed(evt);
            }
        });

        LogoCarroAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Carro_3.png"))); // NOI18N

        javax.swing.GroupLayout AgregarCarroLayout = new javax.swing.GroupLayout(AgregarCarro);
        AgregarCarro.setLayout(AgregarCarroLayout);
        AgregarCarroLayout.setHorizontalGroup(
            AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarCarroLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(LogoCarroAgregar)
                .addGap(37, 37, 37)
                .addComponent(BotonAgregarCarro)
                .addGap(64, 64, 64))
            .addGroup(AgregarCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloAgregarCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AgregarCarroLayout.setVerticalGroup(
            AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCarroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TituloAgregarCarros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AgregarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAgregarCarro)
                    .addComponent(LogoCarroAgregar))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        ListarCarros.setBackground(new java.awt.Color(255, 255, 204));

        TituloListarCarros.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        TituloListarCarros.setForeground(new java.awt.Color(102, 102, 102));
        TituloListarCarros.setText("Listar Carros");
        TituloListarCarros.setToolTipText("");

        BotonListarCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ListarCarros.png"))); // NOI18N
        BotonListarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarCarroActionPerformed(evt);
            }
        });

        CarroLista1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarroLista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AgregarCarro.png"))); // NOI18N

        CarroLista2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarroLista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Carro_4.png"))); // NOI18N

        javax.swing.GroupLayout ListarCarrosLayout = new javax.swing.GroupLayout(ListarCarros);
        ListarCarros.setLayout(ListarCarrosLayout);
        ListarCarrosLayout.setHorizontalGroup(
            ListarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarCarrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloListarCarros)
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarCarrosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CarroLista1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CarroLista2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonListarCarro)
                .addGap(53, 53, 53))
        );
        ListarCarrosLayout.setVerticalGroup(
            ListarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarCarrosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TituloListarCarros)
                .addGroup(ListarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarCarrosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ListarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonListarCarro)
                            .addComponent(CarroLista1)))
                    .addGroup(ListarCarrosLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(CarroLista2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EliminarCarros.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar Carros");

        BotonEliminarCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Prohibido.png"))); // NOI18N
        BotonEliminarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EliminarCarrosLayout = new javax.swing.GroupLayout(EliminarCarros);
        EliminarCarros.setLayout(EliminarCarrosLayout);
        EliminarCarrosLayout.setHorizontalGroup(
            EliminarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarCarrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(EliminarCarrosLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(BotonEliminarCarro)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        EliminarCarrosLayout.setVerticalGroup(
            EliminarCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarCarrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonEliminarCarro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TablaCarrosMenuLayout = new javax.swing.GroupLayout(TablaCarrosMenu);
        TablaCarrosMenu.setLayout(TablaCarrosMenuLayout);
        TablaCarrosMenuLayout.setHorizontalGroup(
            TablaCarrosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaCarrosMenuLayout.createSequentialGroup()
                .addGroup(TablaCarrosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablaCarrosMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloMenuCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TablaCarrosMenuLayout.createSequentialGroup()
                        .addComponent(AgregarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75)
                        .addComponent(ListarCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 484, Short.MAX_VALUE)
                        .addGap(124, 124, 124)
                        .addComponent(EliminarCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65)))
                .addContainerGap())
        );
        TablaCarrosMenuLayout.setVerticalGroup(
            TablaCarrosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaCarrosMenuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(TituloMenuCarros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TablaCarrosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ListarCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EliminarCarros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarCarro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1143, 1143, 1143))
        );

        TablaCarros.addTab("Carros", TablaCarrosMenu);

        TablaInicio.addTab("Carros", TablaCarros);

        TablaPersonalMenu.setBackground(new java.awt.Color(73, 83, 113));

        TituloPersonalVentas.setFont(new java.awt.Font("Bauhaus 93", 0, 120)); // NOI18N
        TituloPersonalVentas.setForeground(new java.awt.Color(255, 255, 255));
        TituloPersonalVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloPersonalVentas.setText("Personal de ventas");

        AgregarPersonal.setBackground(new java.awt.Color(204, 255, 204));

        TituloAgregarPerso.setBackground(new java.awt.Color(102, 102, 102));
        TituloAgregarPerso.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        TituloAgregarPerso.setForeground(new java.awt.Color(102, 102, 102));
        TituloAgregarPerso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloAgregarPerso.setText("Agregar Personal de ventas");

        BotonAgregarPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PersonalVenta_1.png"))); // NOI18N

        javax.swing.GroupLayout AgregarPersonalLayout = new javax.swing.GroupLayout(AgregarPersonal);
        AgregarPersonal.setLayout(AgregarPersonalLayout);
        AgregarPersonalLayout.setHorizontalGroup(
            AgregarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarPersonalLayout.createSequentialGroup()
                .addGroup(AgregarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarPersonalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloAgregarPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AgregarPersonalLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(BotonAgregarPersonal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AgregarPersonalLayout.setVerticalGroup(
            AgregarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloAgregarPerso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAgregarPersonal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListarPersonal.setBackground(new java.awt.Color(255, 255, 204));

        TituloListarPersonal.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        TituloListarPersonal.setForeground(new java.awt.Color(102, 102, 102));
        TituloListarPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloListarPersonal.setText("Listar personal de ventas");

        BotonListarPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ListaPersonal.png"))); // NOI18N
        BotonListarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarPersonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListarPersonalLayout = new javax.swing.GroupLayout(ListarPersonal);
        ListarPersonal.setLayout(ListarPersonalLayout);
        ListarPersonalLayout.setHorizontalGroup(
            ListarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloListarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ListarPersonalLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(BotonListarPersonal)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        ListarPersonalLayout.setVerticalGroup(
            ListarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloListarPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonListarPersonal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EliminarPersonal.setBackground(new java.awt.Color(255, 102, 102));

        TituloEliminarPersonal.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        TituloEliminarPersonal.setForeground(new java.awt.Color(102, 102, 102));
        TituloEliminarPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloEliminarPersonal.setText("Eliminar Personal");

        BotonElimianrPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PersonalVenta_2.png"))); // NOI18N

        javax.swing.GroupLayout EliminarPersonalLayout = new javax.swing.GroupLayout(EliminarPersonal);
        EliminarPersonal.setLayout(EliminarPersonalLayout);
        EliminarPersonalLayout.setHorizontalGroup(
            EliminarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarPersonalLayout.createSequentialGroup()
                .addComponent(TituloEliminarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarPersonalLayout.createSequentialGroup()
                .addGap(0, 140, Short.MAX_VALUE)
                .addComponent(BotonElimianrPersonal)
                .addGap(115, 115, 115))
        );
        EliminarPersonalLayout.setVerticalGroup(
            EliminarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloEliminarPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonElimianrPersonal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TablaPersonalMenuLayout = new javax.swing.GroupLayout(TablaPersonalMenu);
        TablaPersonalMenu.setLayout(TablaPersonalMenuLayout);
        TablaPersonalMenuLayout.setHorizontalGroup(
            TablaPersonalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaPersonalMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloPersonalVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TablaPersonalMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(AgregarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ListarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(EliminarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );
        TablaPersonalMenuLayout.setVerticalGroup(
            TablaPersonalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaPersonalMenuLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(TituloPersonalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TablaPersonalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TablaPersonalMenuLayout.createSequentialGroup()
                        .addGroup(TablaPersonalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ListarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addGap(1217, 1217, 1217))
        );

        TablaPersonalVentas.addTab("Personal de ventas", TablaPersonalMenu);

        TablaInicio.addTab("Personal de ventas", TablaPersonalVentas);

        TablaVentasMenu.setBackground(new java.awt.Color(73, 83, 113));

        jLabel9.setFont(new java.awt.Font("Bauhaus 93", 0, 120)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ventas");
        jLabel9.setToolTipText("");

        AgregarVenta.setBackground(new java.awt.Color(204, 255, 204));

        TituloAgregarVenta.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        TituloAgregarVenta.setForeground(new java.awt.Color(102, 102, 102));
        TituloAgregarVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloAgregarVenta.setText("Agregar Venta");

        BotonAgregarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Venta_1.png"))); // NOI18N
        BotonAgregarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarVentaLayout = new javax.swing.GroupLayout(AgregarVenta);
        AgregarVenta.setLayout(AgregarVentaLayout);
        AgregarVentaLayout.setHorizontalGroup(
            AgregarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarVentaLayout.createSequentialGroup()
                .addGroup(AgregarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarVentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloAgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AgregarVentaLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(BotonAgregarCompra)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AgregarVentaLayout.setVerticalGroup(
            AgregarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarVentaLayout.createSequentialGroup()
                .addComponent(TituloAgregarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonAgregarCompra)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TablaVentasMenuLayout = new javax.swing.GroupLayout(TablaVentasMenu);
        TablaVentasMenu.setLayout(TablaVentasMenuLayout);
        TablaVentasMenuLayout.setHorizontalGroup(
            TablaVentasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaVentasMenuLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TablaVentasMenuLayout.createSequentialGroup()
                .addGap(537, 537, 537)
                .addComponent(AgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(605, Short.MAX_VALUE))
        );
        TablaVentasMenuLayout.setVerticalGroup(
            TablaVentasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaVentasMenuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addComponent(AgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1379, Short.MAX_VALUE))
        );

        TablaVentas.addTab("Ventas", TablaVentasMenu);

        TablaInicio.addTab("Ventas", TablaVentas);

        Configuracion.setBackground(new java.awt.Color(73, 83, 113));

        TituloConfiguracion.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        TituloConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        TituloConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloConfiguracion.setText("Configuración");

        TituloCambiarConce.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        TituloCambiarConce.setForeground(new java.awt.Color(255, 255, 255));
        TituloCambiarConce.setText("Nuevo nombre del concesionario:");
        TituloCambiarConce.setToolTipText("");

        TituloCambiarGerente.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        TituloCambiarGerente.setForeground(new java.awt.Color(255, 255, 255));
        TituloCambiarGerente.setText("Nuevo nombre del gerente:");

        CampoNuevoConce.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        CampoNuevoConce.setForeground(new java.awt.Color(102, 102, 102));
        CampoNuevoConce.setText("Nombre concesionario...");

        CampoNuevoGerente.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        CampoNuevoGerente.setForeground(new java.awt.Color(102, 102, 102));
        CampoNuevoGerente.setText("Nombre gerente...");

        BotonCambiarDatos.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        BotonCambiarDatos.setForeground(new java.awt.Color(255, 255, 255));
        BotonCambiarDatos.setText("OK");
        BotonCambiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambiarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfiguracionLayout = new javax.swing.GroupLayout(Configuracion);
        Configuracion.setLayout(ConfiguracionLayout);
        ConfiguracionLayout.setHorizontalGroup(
            ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ConfiguracionLayout.createSequentialGroup()
                .addGroup(ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConfiguracionLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TituloCambiarConce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TituloCambiarGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoNuevoConce, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(CampoNuevoGerente)))
                    .addGroup(ConfiguracionLayout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(BotonCambiarDatos)))
                .addGap(0, 1000, Short.MAX_VALUE))
        );
        ConfiguracionLayout.setVerticalGroup(
            ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfiguracionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TituloConfiguracion)
                .addGap(39, 39, 39)
                .addGroup(ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloCambiarConce)
                    .addComponent(CampoNuevoConce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloCambiarGerente)
                    .addComponent(CampoNuevoGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(BotonCambiarDatos)
                .addContainerGap(1628, Short.MAX_VALUE))
        );

        TablaConfiguracion.addTab("Configuración", Configuracion);

        TablaInicio.addTab("Configuración", TablaConfiguracion);

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TablaInicio)
                .addContainerGap())
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TablaInicio)
                .addGap(285, 285, 285))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(255, 251, 233));
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Carro1.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Personal venta.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Venta.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator1);

        jButton4.setText("EXIT");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        escritorio.setBackground(new java.awt.Color(102, 102, 102));
        escritorio.setForeground(new java.awt.Color(0, 51, 255));

        Contenedor.setLayout(new java.awt.BorderLayout());

        escritorio.setLayer(Contenedor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Adicionar");

        jMenuCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Carro1.png"))); // NOI18N
        jMenuCarro.setText("Carro");
        jMenuCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarroActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCarro);

        jMenuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Personal venta.png"))); // NOI18N
        jMenuPersonal.setText("Personal");
        jMenuPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPersonalActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPersonal);

        jMenuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Venta.png"))); // NOI18N
        jMenuVentas.setText("Ventas");
        jMenu1.add(jMenuVentas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Eliminar");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Carro1.png"))); // NOI18N
        jMenuItem4.setText("Carro");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Personal venta.png"))); // NOI18N
        jMenuItem5.setText("Personal");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Listar");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Carro1.png"))); // NOI18N
        jMenuItem6.setText("Carros");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Personal venta.png"))); // NOI18N
        jMenuItem7.setText("Personal");
        jMenu3.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Venta.png"))); // NOI18N
        jMenuItem8.setText("Ventas");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1166, Short.MAX_VALUE)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void mensajeAlerta(String mensaje, String Alerta) {
        JOptionPane.showMessageDialog(null, mensaje, Alerta, JOptionPane.INFORMATION_MESSAGE);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

  AddCarros.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarroActionPerformed
        // TODO add your handling code here:
         AddCarros.setVisible(true);
    }//GEN-LAST:event_jMenuCarroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPersonalActionPerformed
        this.escritorio.add(retornoVistas.returnInternal(new AddPersonal(), "Adicionar Personal"));
        
        
 
    }//GEN-LAST:event_jMenuPersonalActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        listarCarros.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void listarCarros(){
        modelo = (DefaultTableModel) tablaDatos.getModel() ;
        Carros carro = new Carros();
        
        int filas = modelo.getRowCount();
        for(int i=0;i<filas;i++){
            modelo.removeRow(0);
        }
        
        for(int i=0;i<Consecionario.listaCarros.size();i++){
            carro = Consecionario.listaCarros.get(i);
            modelo.addRow(new Object[]{carro.getCodigo(),carro.getMarca(),carro.getModelo(),carro.getColor(),carro.getPrecio()});
        }
        
    }
    
    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:}
        boolean bandera = false;
        String ruta = eliminarAutoTextField.getText();
        for (Carros carro : Consecionario.listaCarros) {
            if (carro.getCodigo().equals(ruta)) {
                bandera = true;
                System.out.println("FUNCIONA");
            } else {
                System.out.println("NO FUNCIONA");
                System.out.println(carro.getCodigo());
            }
        }
        if (bandera == true) {
            mensajeAlerta("Auto Encontrado","MOSTRAR AUTOS");
            Consecionario.listaCarros.remove(ruta);
        }else{
            mensajeAlerta("ERROR, Auto no Encontrado","MOSTRAR AUTOS");
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void textColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textColorActionPerformed

    private void textModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textModeloActionPerformed

    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButtonActionPerformed
        dispose();
    }//GEN-LAST:event_atrasButtonActionPerformed

    private void textCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoActionPerformed

    private void textPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrecioActionPerformed

    private void comboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMarcaActionPerformed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed

        double precio = Double.parseDouble(textPrecio.getText());
        String marca = comboMarca.getSelectedItem().toString();
        String modeloC = textModelo.getText();
        String color = textColor.getText();
        String codigo = textCodigo.getText();

        Consecionario.listaCarros.add(new Carros(precio, marca, modeloC, color, codigo));

        textPrecio.setText("");
        textModelo.setText("");
        textColor.setText("");
        textCodigo.setText("");

        mensajeAlerta("Nuevo Auto Agregado", "Agregar Carros");
        listarCarros();
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void EnviarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarInformacionActionPerformed
        String nombreConce = CampoNombreConcesionario1.getText();
        concesionario.setNombreConsecionario(nombreConce);
        TituloNombreConce.setText("Concesionario de " + concesionario.getNombreConsecionario());
        TituloNombreConce1.setText("Concesionario de " + concesionario.getNombreConsecionario());
        String nombreGerente = CampoNombreGerente.getText();
        concesionario.setDueño(nombreGerente);
        TituloNombreGerente.setText("Gerente: " + concesionario.getDueño());
        
        MenuInicio.setVisible(false);
         Contenedor.add(MenuPrincipal);
        MenuPrincipal.setVisible(true);
        
    }//GEN-LAST:event_EnviarInformacionActionPerformed

    private void CampoNombreConcesionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreConcesionario1ActionPerformed
        
    }//GEN-LAST:event_CampoNombreConcesionario1ActionPerformed

    private void CampoNombreGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreGerenteActionPerformed
       
    }//GEN-LAST:event_CampoNombreGerenteActionPerformed

    private void BotonAgregarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarCarroActionPerformed

    private void BotonListarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonListarCarroActionPerformed

    private void BotonEliminarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarCarroActionPerformed

    private void BotonListarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonListarPersonalActionPerformed

    private void BotonAgregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarCompraActionPerformed

    private void BotonCambiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambiarDatosActionPerformed
        String nombreConce = CampoNuevoConce.getText();
        concesionario.setNombreConsecionario(nombreConce);
        TituloNombreConce.setText("Concesionario de " + concesionario.getNombreConsecionario());
        TituloNombreConce1.setText("Concesionario de " + concesionario.getNombreConsecionario());
        String nombreGerente = CampoNuevoGerente.getText();
        concesionario.setDueño(nombreGerente);
        TituloNombreGerente.setText("Gerente: " + concesionario.getDueño());
       mensajeAlerta("Datos cambiados exitosamente", "Cambiar datos");
    }//GEN-LAST:event_BotonCambiarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddCarroTitulo;
    private javax.swing.JFrame AddCarros;
    private javax.swing.JPanel AgregarCarro;
    private javax.swing.JPanel AgregarPersonal;
    private javax.swing.JPanel AgregarVenta;
    private javax.swing.JLabel BienvenidaInicio;
    private javax.swing.JButton BotonAgregarCarro;
    private javax.swing.JButton BotonAgregarCompra;
    private javax.swing.JButton BotonAgregarPersonal;
    private javax.swing.JButton BotonCambiarDatos;
    private javax.swing.JButton BotonElimianrPersonal;
    private javax.swing.JButton BotonEliminarCarro;
    private javax.swing.JButton BotonListarCarro;
    private javax.swing.JButton BotonListarPersonal;
    private javax.swing.JTextField CampoNombreConcesionario1;
    private javax.swing.JTextField CampoNombreGerente;
    private javax.swing.JTextField CampoNuevoConce;
    private javax.swing.JTextField CampoNuevoGerente;
    private javax.swing.JLabel CarroLista1;
    private javax.swing.JLabel CarroLista2;
    private javax.swing.JPanel Configuracion;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel EliminarCarros;
    private javax.swing.JPanel EliminarPersonal;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JButton EnviarInformacion;
    private javax.swing.JLabel Gerente;
    private javax.swing.JLabel ImagenAddcarro;
    private javax.swing.JPanel ListarCarros;
    private javax.swing.JPanel ListarPersonal;
    private javax.swing.JLabel LogoCarroAgregar;
    private javax.swing.JPanel MenuInicio;
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JLabel Rueda;
    private javax.swing.JLabel Sonrisa;
    private javax.swing.JTabbedPane TablaBienvenida;
    private javax.swing.JTabbedPane TablaCarros;
    private javax.swing.JPanel TablaCarrosMenu;
    private javax.swing.JTabbedPane TablaConfiguracion;
    private javax.swing.JTabbedPane TablaInicio;
    private javax.swing.JPanel TablaInicioBienvenida;
    private javax.swing.JPanel TablaPersonalMenu;
    private javax.swing.JTabbedPane TablaPersonalVentas;
    private javax.swing.JTabbedPane TablaVentas;
    private javax.swing.JPanel TablaVentasMenu;
    private javax.swing.JLabel TituloAgregarCarros;
    private javax.swing.JLabel TituloAgregarPerso;
    private javax.swing.JLabel TituloAgregarVenta;
    private javax.swing.JLabel TituloCambiarConce;
    private javax.swing.JLabel TituloCambiarGerente;
    private javax.swing.JLabel TituloConce;
    private javax.swing.JLabel TituloConfiguracion;
    private javax.swing.JLabel TituloEliminarPersonal;
    private javax.swing.JLabel TituloListarCarros;
    private javax.swing.JLabel TituloListarPersonal;
    private javax.swing.JLabel TituloMenuCarros;
    private javax.swing.JLabel TituloNombreConce;
    private javax.swing.JLabel TituloNombreConce1;
    private javax.swing.JLabel TituloNombreGerente;
    private javax.swing.JLabel TituloPersonalVentas;
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton atrasButton;
    private javax.swing.JTextField cantidadAutos;
    private javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JTextField eliminarAutoTextField;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCarro;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuPersonal;
    private javax.swing.JMenuItem jMenuVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JFrame listarCarros;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textColor;
    private javax.swing.JTextField textModelo;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables
    ReturnViews retornoVistas = new ReturnViews();
}
